# Generated by Django 3.2.2 on 2022-11-17 23:05

import ckeditor.fields
import cloudinary_storage.storage
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('last_modified', models.DateField(auto_now=True)),
                ('category', models.CharField(blank=True, max_length=50, null=True)),
                ('title', models.CharField(max_length=150)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/contents')),
                ('image_url', models.CharField(blank=True, max_length=2500, null=True)),
                ('content', ckeditor.fields.RichTextField(max_length=20000)),
                ('quote', models.CharField(blank=True, max_length=250, null=True)),
                ('ad', models.TextField(blank=True, max_length=2000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('age', models.PositiveIntegerField(blank=True, null=True)),
                ('location', models.CharField(max_length=30)),
                ('profession', models.CharField(max_length=30)),
                ('my_image', models.ImageField(blank=True, null=True, upload_to='images/about')),
                ('about_me', models.TextField(max_length=500)),
                ('about_services', models.TextField(blank=True, max_length=2000, null=True)),
                ('about_team', models.TextField(blank=True, max_length=1000, null=True)),
                ('CV', models.FileField(blank=True, null=True, storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(), upload_to='documents')),
                ('address', models.CharField(max_length=150)),
                ('email_1', models.EmailField(max_length=254)),
                ('email_2', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone_1', models.CharField(max_length=20)),
                ('phone_2', models.CharField(blank=True, max_length=20, null=True)),
                ('phone_3', models.CharField(blank=True, max_length=20, null=True)),
                ('whatsapp_link', models.URLField(blank=True, max_length=300, null=True)),
                ('facebook_link', models.URLField(blank=True, max_length=300, null=True)),
                ('twitter_link', models.URLField(blank=True, max_length=300, null=True)),
                ('instagram_link', models.URLField(blank=True, max_length=300, null=True)),
                ('tiktok_link', models.URLField(blank=True, max_length=300, null=True)),
                ('linkedin_link', models.URLField(blank=True, max_length=300, null=True)),
                ('youtube_link', models.URLField(blank=True, max_length=300, null=True)),
                ('pin_interest_link', models.URLField(blank=True, max_length=300, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.PositiveIntegerField(blank=True, null=True)),
                ('subject', models.CharField(max_length=100)),
                ('message', models.TextField(max_length=10000)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PortfolioCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('web-design', 'web design'), ('web-development', 'web development'), ('graphic-design', 'graphic design'), ('product', 'product'), ('service', 'service'), ('book', 'book')], default='graphic-design', max_length=25, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.CharField(max_length=50)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/services')),
                ('detail', models.TextField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='images/team')),
                ('role', models.CharField(max_length=50)),
                ('skill1', models.CharField(blank=True, max_length=25, null=True)),
                ('skill2', models.CharField(blank=True, max_length=25, null=True)),
                ('skill3', models.CharField(blank=True, max_length=25, null=True)),
                ('whatsapp_link', models.URLField(blank=True, max_length=300, null=True)),
                ('facebook_link', models.URLField(blank=True, max_length=300, null=True)),
                ('twitter_link', models.URLField(blank=True, max_length=300, null=True)),
                ('instagram_link', models.URLField(blank=True, max_length=300, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=100)),
                ('client_image', models.ImageField(upload_to='images/testimonials')),
                ('service', models.CharField(max_length=50)),
                ('testimony', models.CharField(max_length=3000)),
                ('company', models.CharField(blank=True, max_length=100, null=True)),
                ('website', models.CharField(blank=True, max_length=100, null=True)),
                ('website_url', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('author', models.CharField(blank=True, max_length=25, null=True)),
                ('image', models.ImageField(upload_to='images/portfolios')),
                ('detail', models.TextField(blank=True, max_length=1500, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='portfolioApp.portfoliocategory')),
            ],
        ),
    ]
