# Generated by Django 3.2.2 on 2022-04-07 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='websitesetting',
            name='analytics',
            field=models.TextField(blank=True, max_length=1500),
        ),
    ]
