# Generated by Django 3.2.2 on 2022-11-08 00:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioApp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WebsiteSetting',
        ),
    ]
