# Generated by Django 3.2.2 on 2022-04-07 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioApp', '0002_websitesetting_analytics'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='image',
            field=models.ImageField(upload_to='images/team'),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='client_image',
            field=models.ImageField(default=2, upload_to='images/testimonials'),
            preserve_default=False,
        ),
    ]
