# Generated by Django 3.2.2 on 2022-04-07 03:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioApp', '0003_auto_20220407_0240'),
    ]

    operations = [
        migrations.RenameField(
            model_name='websitesetting',
            old_name='analytics',
            new_name='google_analytics',
        ),
    ]
