# Generated by Django 3.2.2 on 2022-04-07 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioApp', '0004_rename_analytics_websitesetting_google_analytics'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='phone_1',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='info',
            name='phone_2',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='info',
            name='phone_3',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
