# Generated by Django 3.2.2 on 2022-04-08 02:52

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioApp', '0006_alter_message_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('last_modified', models.DateField(auto_now=True)),
                ('category', models.CharField(blank=True, max_length=50, null=True)),
                ('title', models.CharField(max_length=150)),
                ('image', models.ImageField(blank=True, upload_to='images/contents')),
                ('content', ckeditor.fields.RichTextField(max_length=20000)),
                ('quote', models.CharField(blank=True, max_length=250, null=True)),
                ('ad', models.TextField(blank=True, max_length=2000, null=True)),
            ],
        ),
    ]
