# Generated by Django 3.2.2 on 2022-04-19 11:47

import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioApp', '0007_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='CV',
            field=models.FileField(blank=True, storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(), upload_to='documents'),
        ),
    ]
