# Generated by Django 3.2.2 on 2010-01-04 22:26

import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioApp', '0008_alter_info_cv'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='image_url',
            field=models.CharField(blank=True, max_length=2500, null=True),
        ),
        migrations.AlterField(
            model_name='content',
            name='image',
            field=models.ImageField(blank=True, upload_to='violetportfolio/images/contents'),
        ),
        migrations.AlterField(
            model_name='info',
            name='CV',
            field=models.FileField(blank=True, storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(), upload_to='violetportfolio/documents'),
        ),
        migrations.AlterField(
            model_name='info',
            name='my_image',
            field=models.ImageField(blank=True, upload_to='violetportfolio/images/about'),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='image',
            field=models.ImageField(upload_to='violetportfolio/images/portfolio'),
        ),
        migrations.AlterField(
            model_name='service',
            name='image',
            field=models.ImageField(blank=True, upload_to='violetportfolio/images/services'),
        ),
        migrations.AlterField(
            model_name='team',
            name='image',
            field=models.ImageField(upload_to='violetportfolio/images/team'),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='client_image',
            field=models.ImageField(upload_to='violetportfolio/images/testimonials'),
        ),
        migrations.AlterField(
            model_name='websitesetting',
            name='logo',
            field=models.ImageField(blank=True, upload_to='violetportfolio/images/setting'),
        ),
    ]
