# Generated by Django 3.2.2 on 2022-10-18 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioApp', '0010_auto_20220913_0653'),
    ]

    operations = [
        migrations.RenameField(
            model_name='info',
            old_name='facebook',
            new_name='facebook_link',
        ),
        migrations.RenameField(
            model_name='info',
            old_name='instagram',
            new_name='instagram_link',
        ),
        migrations.RenameField(
            model_name='info',
            old_name='linked_in',
            new_name='linkedin_link',
        ),
        migrations.RenameField(
            model_name='info',
            old_name='pin_interest',
            new_name='pin_interest_link',
        ),
        migrations.RenameField(
            model_name='info',
            old_name='tiktok',
            new_name='tiktok_link',
        ),
        migrations.RenameField(
            model_name='info',
            old_name='twitter',
            new_name='twitter_link',
        ),
        migrations.RenameField(
            model_name='info',
            old_name='whatsapp',
            new_name='whatsapp_link',
        ),
        migrations.RenameField(
            model_name='info',
            old_name='youtube',
            new_name='youtube_link',
        ),
        migrations.RenameField(
            model_name='team',
            old_name='facebook',
            new_name='facebook_link',
        ),
        migrations.RenameField(
            model_name='team',
            old_name='instagram',
            new_name='instagram_link',
        ),
        migrations.RenameField(
            model_name='team',
            old_name='twitter',
            new_name='twitter_link',
        ),
        migrations.RenameField(
            model_name='team',
            old_name='whatsapp',
            new_name='whatsapp_link',
        ),
    ]
